name: foundation-01-remote-state

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - 'terraform/01-digitalocean-remote-state/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    env:
      # DigitalOcean Spaces bucket name, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      # AWS variables, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # DigitalOcean token used for CRUD on the DigitalOcean project, a general spaces access key and spaces bucket. 
      TF_VAR_do_token: ${{ secrets.01_DIGITALOCEAN_TOKEN }}

      # DigitalOcean variables, added when creating the github repository through terraform in 03-github-foundation-repo.yml
      TF_VAR_project_name: ${{ vars.DO_ORGANISATION_PROJECT_NAME }}
      TF_VAR_project_description: ${{ vars.DO_ORGANISATION_PROJECT_DESCRIPTION }}
      TF_VAR_project_purpose: ${{ vars.DO_ORGANISATION_PROJECT_PURPOSE }}
      TF_VAR_project_environment: ${{ vars.DO_ORGANISATION_PROJECT_ENVIRONMENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply remote state stack
        working-directory: terraform/01-digitalocean-remote-state
        run: |
          chmod +x ./apply.sh
          ./apply.sh


